// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: yfs.proto

package yfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileSystemHeader contains the root directory and system metadata
type FileSystemHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	BlockSize     uint32                 `protobuf:"varint,2,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	Root          *DirectoryEntry        `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSystemHeader) Reset() {
	*x = FileSystemHeader{}
	mi := &file_yfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSystemHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSystemHeader) ProtoMessage() {}

func (x *FileSystemHeader) ProtoReflect() protoreflect.Message {
	mi := &file_yfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSystemHeader.ProtoReflect.Descriptor instead.
func (*FileSystemHeader) Descriptor() ([]byte, []int) {
	return file_yfs_proto_rawDescGZIP(), []int{0}
}

func (x *FileSystemHeader) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FileSystemHeader) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *FileSystemHeader) GetRoot() *DirectoryEntry {
	if x != nil {
		return x.Root
	}
	return nil
}

// FileMetadata contains common metadata for files and directories
type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ModTime       int64                  `protobuf:"varint,2,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_yfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_yfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_yfs_proto_rawDescGZIP(), []int{1}
}

func (x *FileMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileMetadata) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

// FileEntry_pb represents a file in the protobuf format
type FileEntryPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *FileMetadata          `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	FirstBlockId  uint32                 `protobuf:"varint,2,opt,name=first_block_id,json=firstBlockId,proto3" json:"first_block_id,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntryPb) Reset() {
	*x = FileEntryPb{}
	mi := &file_yfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntryPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntryPb) ProtoMessage() {}

func (x *FileEntryPb) ProtoReflect() protoreflect.Message {
	mi := &file_yfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntryPb.ProtoReflect.Descriptor instead.
func (*FileEntryPb) Descriptor() ([]byte, []int) {
	return file_yfs_proto_rawDescGZIP(), []int{2}
}

func (x *FileEntryPb) GetMetadata() *FileMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FileEntryPb) GetFirstBlockId() uint32 {
	if x != nil {
		return x.FirstBlockId
	}
	return 0
}

func (x *FileEntryPb) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// DirectoryEntry represents a directory with files and subdirectories
type DirectoryEntry struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Metadata      *FileMetadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Files         map[string]*FileEntryPb    `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Directories   map[string]*DirectoryEntry `protobuf:"bytes,3,rep,name=directories,proto3" json:"directories,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryEntry) Reset() {
	*x = DirectoryEntry{}
	mi := &file_yfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryEntry) ProtoMessage() {}

func (x *DirectoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_yfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryEntry.ProtoReflect.Descriptor instead.
func (*DirectoryEntry) Descriptor() ([]byte, []int) {
	return file_yfs_proto_rawDescGZIP(), []int{3}
}

func (x *DirectoryEntry) GetMetadata() *FileMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DirectoryEntry) GetFiles() map[string]*FileEntryPb {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *DirectoryEntry) GetDirectories() map[string]*DirectoryEntry {
	if x != nil {
		return x.Directories
	}
	return nil
}

var File_yfs_proto protoreflect.FileDescriptor

const file_yfs_proto_rawDesc = "" +
	"\n" +
	"\tyfs.proto\x12\x03yfs\"t\n" +
	"\x10FileSystemHeader\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"block_size\x18\x02 \x01(\rR\tblockSize\x12'\n" +
	"\x04root\x18\x03 \x01(\v2\x13.yfs.DirectoryEntryR\x04root\"=\n" +
	"\fFileMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bmod_time\x18\x02 \x01(\x03R\amodTime\"w\n" +
	"\fFileEntry_pb\x12-\n" +
	"\bmetadata\x18\x01 \x01(\v2\x11.yfs.FileMetadataR\bmetadata\x12$\n" +
	"\x0efirst_block_id\x18\x02 \x01(\rR\ffirstBlockId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\xdf\x02\n" +
	"\x0eDirectoryEntry\x12-\n" +
	"\bmetadata\x18\x01 \x01(\v2\x11.yfs.FileMetadataR\bmetadata\x124\n" +
	"\x05files\x18\x02 \x03(\v2\x1e.yfs.DirectoryEntry.FilesEntryR\x05files\x12F\n" +
	"\vdirectories\x18\x03 \x03(\v2$.yfs.DirectoryEntry.DirectoriesEntryR\vdirectories\x1aK\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.yfs.FileEntry_pbR\x05value:\x028\x01\x1aS\n" +
	"\x10DirectoriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.yfs.DirectoryEntryR\x05value:\x028\x01B\aZ\x05./yfsb\x06proto3"

var (
	file_yfs_proto_rawDescOnce sync.Once
	file_yfs_proto_rawDescData []byte
)

func file_yfs_proto_rawDescGZIP() []byte {
	file_yfs_proto_rawDescOnce.Do(func() {
		file_yfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yfs_proto_rawDesc), len(file_yfs_proto_rawDesc)))
	})
	return file_yfs_proto_rawDescData
}

var file_yfs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_yfs_proto_goTypes = []any{
	(*FileSystemHeader)(nil), // 0: yfs.FileSystemHeader
	(*FileMetadata)(nil),     // 1: yfs.FileMetadata
	(*FileEntryPb)(nil),      // 2: yfs.FileEntry_pb
	(*DirectoryEntry)(nil),   // 3: yfs.DirectoryEntry
	nil,                      // 4: yfs.DirectoryEntry.FilesEntry
	nil,                      // 5: yfs.DirectoryEntry.DirectoriesEntry
}
var file_yfs_proto_depIdxs = []int32{
	3, // 0: yfs.FileSystemHeader.root:type_name -> yfs.DirectoryEntry
	1, // 1: yfs.FileEntry_pb.metadata:type_name -> yfs.FileMetadata
	1, // 2: yfs.DirectoryEntry.metadata:type_name -> yfs.FileMetadata
	4, // 3: yfs.DirectoryEntry.files:type_name -> yfs.DirectoryEntry.FilesEntry
	5, // 4: yfs.DirectoryEntry.directories:type_name -> yfs.DirectoryEntry.DirectoriesEntry
	2, // 5: yfs.DirectoryEntry.FilesEntry.value:type_name -> yfs.FileEntry_pb
	3, // 6: yfs.DirectoryEntry.DirectoriesEntry.value:type_name -> yfs.DirectoryEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_yfs_proto_init() }
func file_yfs_proto_init() {
	if File_yfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yfs_proto_rawDesc), len(file_yfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yfs_proto_goTypes,
		DependencyIndexes: file_yfs_proto_depIdxs,
		MessageInfos:      file_yfs_proto_msgTypes,
	}.Build()
	File_yfs_proto = out.File
	file_yfs_proto_goTypes = nil
	file_yfs_proto_depIdxs = nil
}
